language: csharp
solution: cs-prog-ws.sln
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore
 - dotnet build
 #- dotnet test ./Tests/Tests.csproj
 # Uncomment next line for testing Ex1
 - dotnet test ./Tests/Tests.csproj --filter "FullyQualifiedName~Tests.Ex1Tests"